services:
  rabbitmq:
    image: 'rabbitmq:3.10.25-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=data_ingestion_engine'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'