spring:
  application:
    name: configuration-service

  datasource:
    url: jdbc:postgresql://localhost:5432/config
    username: config_user
    password: secret1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
