server:
  port: 8084

spring:
  application:
    name: report-generator-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ingestor
    username: ingestor_user
    password: secret2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
