server:
  port: 8082

spring:
  application:
    name: ingestion-service
  cloud:
    openfeign:
      client:
        config:
          configuration-service:
            url: http://localhost:8081

  datasource:
    url: jdbc:postgresql://localhost:5432/ingestion
    username: ingestor_user
    password: secret2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yaml
    default-schema: public

storage:
  path: /tmp

rabbitmq:
  host: localhost
  port: 5672
  username: myuser
  password: secret
  exchanges:
    ingestion: ingestion.exchange
  queues:
    report-generator: report-generator.queue
    notification: notification.queue
---
spring:
  config:
    activate:
      on-profile: test
  liquibase:
    enabled: false
