server:
  port: 8082

spring:
  application:
    name: ingestor-service
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          configuration-service:
            url: http://localhost:8081

  datasource:
    url: jdbc:postgresql://localhost:5433/ingestion
    username: ingestor_user
    password: secret2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yaml

storage:
  path: /tmp

rabbitmq:
  host: localhost
  port: 5672
  username: myuser
  password: secret
  exchanges:
    data-ingested: data.ingested.exchange
    file-upload: file.upload.exchange
  queues:
    file-upload: file.upload.queue
