server:
  port: 8080

spring:
  application:
    name: producer-service

storage:
  path: /tmp

rabbitmq:
  host: localhost
  port: 5672
  username: myuser
  password: secret
  exchanges:
    file-upload: file.upload.exchange

